services:
  - type: web
    name: salary-telegram-bot
    runtime: docker
    dockerfilePath: SalaryTelegramBot.Api/Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_USER_ID
        sync: false
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: salary-postgres
          property: connectionString
    dependsOn:
      - salary-postgres

  - type: pgsql
    name: salary-postgres
    database: salary_bot
    plan: free
