services:
  - type: web
    name: salary-telegram-bot
    runtime: docker
    dockerfilePath: SalaryTelegramBot.Api/Dockerfile
    envVars:
      - key: TELEGRAM__Token
        sync: false
      - key: TELEGRAM__AdminUserIds__0
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
