// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalaryTelegramBot.Api.Data;

#nullable disable

namespace SalaryTelegramBot.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615125750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalaryTelegramBot.Api.Models.AccrualRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "DayOfMonth")
                        .IsUnique();

                    b.ToTable("AccrualRules");
                });

            modelBuilder.Entity("SalaryTelegramBot.Api.Models.BotSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalculationStartDay")
                        .HasColumnType("integer");

                    b.Property<int?>("CalculationStartMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("CalculationStartYear")
                        .HasColumnType("integer");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("CheckHour")
                        .HasColumnType("integer");

                    b.Property<int>("CheckMinute")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNdflEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("NdflStartDay")
                        .HasColumnType("integer");

                    b.Property<int?>("NdflStartMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("NdflStartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("SalaryTelegramBot.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
