// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryTelegramBot.Api.Data;

#nullable disable

namespace SalaryTelegramBot.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("SalaryTelegramBot.Api.Models.AccrualRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "DayOfMonth")
                        .IsUnique();

                    b.ToTable("AccrualRules");
                });

            modelBuilder.Entity("SalaryTelegramBot.Api.Models.BotSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalculationStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalculationStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalculationStartYear")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckMinute")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNdflEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NdflStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NdflStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NdflStartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("SalaryTelegramBot.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
